/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.DesktopApp.form.i_l;

import com.DesktopApp.Controller.SessionController;
import com.DesktopApp.ConstantUtils.ConstantMessages;
import com.DesktopApp.ConstantUtils.WindowsManager;
import com.DesktopApp.form.GUI.NewMDIApplication;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class LoginForm_1 extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm_1
     */
    public LoginForm_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dPanel1 = new com.itgp.mvc.DPanel();
        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio Sesión");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 40));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/DesktopApp/Icon/cancel.png"))); // NOI18N
        btnClose.setText("Cancelar");
        btnClose.setPreferredSize(new java.awt.Dimension(120, 30));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose);

        btnAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/DesktopApp/Icon/accept_1.png"))); // NOI18N
        btnAccept.setText("Aceptar");
        btnAccept.setPreferredSize(new java.awt.Dimension(120, 30));
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccept);

        dPanel1.add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(384, 100));
        jPanel2.setLayout(null);

        lblPassword.setText("Contraseña");
        jPanel2.add(lblPassword);
        lblPassword.setBounds(20, 60, 110, 25);

        lblName.setText("Usuario");
        jPanel2.add(lblName);
        lblName.setBounds(20, 20, 110, 25);
        jPanel2.add(txtPassword);
        txtPassword.setBounds(130, 60, 230, 25);
        jPanel2.add(txtUser);
        txtUser.setBounds(130, 20, 230, 25);

        dPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(dPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        if (validateData()) {
            try {
                if (SessionController.beginSession(txtUser.getText(), txtPassword.getText())) {
                    displayForm();
                } else {
                    JOptionPane.showMessageDialog(null, ConstantMessages.INCORRECT_PASSWORD,
                            ConstantMessages.ERROR_TITLE, ConstantMessages.ERROR_ICON);
                }
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(LoginForm_1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }



    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnClose;
    private com.itgp.mvc.DPanel dPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private void displayForm() {
        /*PrincipalForm n = new PrincipalForm();
         n.setVisible(true);
         n.setExtendedState(n.MAXIMIZED_BOTH);
         WindowsManager.set(n);
         this.dispose();*/

        NewMDIApplication n = new NewMDIApplication();
        n.setVisible(true);
        n.setExtendedState(n.MAXIMIZED_BOTH);
        WindowsManager.set(n);
        this.dispose();

    }

    private boolean validateData() {

        if (txtUser.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, ConstantMessages.REQUIRED_USERNAME,
                    ConstantMessages.ERROR_TITLE, ConstantMessages.ERROR_ICON);
            txtUser.requestFocus();
            return false;
        }

        if (txtPassword.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, ConstantMessages.REQUIRED_PASSWORD,
                    ConstantMessages.ERROR_TITLE, ConstantMessages.ERROR_ICON);
            txtPassword.requestFocus();
            return false;
        }

        return true;
    }
}
