package com.DesktopApp.form.i_l;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import com.DesktopApp.Factory.FactoryLookAndFeel;
import com.DesktopApp.InternalFrame.BaseJInternalFrame;
import com.DesktopApp.ConstantUtils.WindowsManager;
import com.DesktopApp.ConstantUtils.ConstantsLookAndFeel;
import com.DesktopApp.ConstantUtils.Prefs;
import com.itgp.mvc.DSetErrorEvent;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author jdsoft
 */
public class LookAndFeelForm extends BaseJInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public LookAndFeelForm() {
        super("Look And Feel", "Seleecione un tema por cambiar");
        initComponents();
        setComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dPanel2 = new com.itgp.mvc.DPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cmbLookAndFeel = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(514, 216));

        dPanel2.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.add(cmbLookAndFeel);

        dPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jButton1.setText("jButton1");
        jPanel4.add(jButton1);

        btnAceptar.setText("Aceptar");
        btnAceptar.setPreferredSize(new java.awt.Dimension(95, 25));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel4.add(btnAceptar);

        dPanel2.add(jPanel4, java.awt.BorderLayout.SOUTH);

        getContentPane().add(dPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String lookAndFeel = (String) cmbLookAndFeel.getSelectedItem();
        try {
            UIManager.setLookAndFeel((FactoryLookAndFeel.getLookAndFeel(lookAndFeel)));
            SwingUtilities.updateComponentTreeUI(WindowsManager.get());
            Prefs.put("lookAndFeel", lookAndFeel);
        } catch (UnsupportedLookAndFeelException | ParseException ex) {
            Logger.getLogger(LookAndFeelForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox cmbLookAndFeel;
    private com.itgp.mvc.DPanel dPanel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    private void setComboBox() {
        DefaultComboBoxModel model = new DefaultComboBoxModel(ConstantsLookAndFeel.getLookAndFeel());
        cmbLookAndFeel.setModel(model);
    }
}
