/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.DesktopApp.form.e_h;

import com.DesktopApp.Utils.GeneralUtility;
import com.DesktopApp.Utils.ImageUtil;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.internet.AddressException;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author Jonathan
 */
public class ErrorForm extends JDialog {

    /**
     * Creates new form ErrorForm
     */
    private String path;

    public ErrorForm(JFrame parent, String error) {
        super(parent, true);
        initComponents();
        setError(error);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dPanel1 = new com.itgp.mvc.DPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtError = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(610, 294));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtError.setColumns(20);
        txtError.setRows(5);
        jScrollPane1.setViewportView(txtError);

        dPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(319, 44));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/DesktopApp/Icon/sendEmail.png"))); // NOI18N
        btnAdd.setText("Enviar");
        btnAdd.setPreferredSize(new java.awt.Dimension(120, 30));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);

        dPanel1.add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setPreferredSize(new java.awt.Dimension(135, 100));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/DesktopApp/Icon/error.png"))); // NOI18N
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        dPanel1.add(jPanel2, java.awt.BorderLayout.WEST);

        getContentPane().add(dPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        send();

    }//GEN-LAST:event_btnAddActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private com.itgp.mvc.DPanel dPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtError;
    // End of variables declaration//GEN-END:variables

    private void setError(String error) {
        txtError.setText(error);
    }

    private void send() {
        try {
            String error;
            String exceptionType;

            error = txtError.getText();
            exceptionType = txtError.getText().getClass().getName();
            path = ImageUtil.getScreenshoot();
            
            GeneralUtility.sendEmail(error, exceptionType);
        } catch (AddressException ex) {
            Logger.getLogger(ErrorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
