/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.DesktopApp.form.t_w;

import com.DesktopApp.Controller.UserController;
import com.DesktopApp.Entity.User;
import com.DesktopApp.InternalFrame.BaseJDialog;
import javax.swing.JFrame;

/**
 *
 * @author Jonathan
 */
public class UserForm extends BaseJDialog {

    /**
     * Creates new form UserForm
     */
    private Integer id;

    public UserForm(JFrame parent, Integer id) {
        super(parent, true, "", "");
        this.id = id;
        initComponents();
        customInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dPanel1 = new com.itgp.mvc.DPanel();
        jPanel2 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblName1 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblName2 = new javax.swing.JLabel();
        txtCellPhone = new javax.swing.JTextField();
        lblName3 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblName4 = new javax.swing.JLabel();
        lblName5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(508, 440));

        jPanel2.setLayout(null);
        jPanel2.add(txtName);
        txtName.setBounds(120, 20, 340, 25);

        lblName.setText("Nombre");
        jPanel2.add(lblName);
        lblName.setBounds(10, 20, 110, 25);
        jPanel2.add(txtFirstName);
        txtFirstName.setBounds(120, 60, 340, 25);

        lblName1.setText("Primer Apellido");
        jPanel2.add(lblName1);
        lblName1.setBounds(10, 60, 110, 25);
        jPanel2.add(txtLastName);
        txtLastName.setBounds(120, 100, 340, 25);

        lblName2.setText("Segundo Apellido");
        jPanel2.add(lblName2);
        lblName2.setBounds(10, 100, 110, 25);
        jPanel2.add(txtCellPhone);
        txtCellPhone.setBounds(120, 220, 340, 25);

        lblName3.setText("Tel.Celular");
        jPanel2.add(lblName3);
        lblName3.setBounds(10, 220, 110, 25);
        jPanel2.add(txtPhone);
        txtPhone.setBounds(120, 180, 340, 25);

        lblName4.setText("Tel.Casa");
        jPanel2.add(lblName4);
        lblName4.setBounds(10, 180, 110, 25);

        lblName5.setText("Correo Electrónico");
        jPanel2.add(lblName5);
        lblName5.setBounds(10, 140, 110, 25);
        jPanel2.add(txtEmail);
        txtEmail.setBounds(120, 140, 340, 25);

        dPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        btnClose.setText("Cerrar");
        btnClose.setPreferredSize(new java.awt.Dimension(95, 25));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel3.add(btnClose);

        btnAdd.setText("Actualizar");
        btnAdd.setPreferredSize(new java.awt.Dimension(95, 25));
        jPanel3.add(btnAdd);

        dPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(dPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private com.itgp.mvc.DPanel dPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblName5;
    private javax.swing.JTextField txtCellPhone;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

    private void customInit() {
        User user = UserController.getUserById(id);

        txtName.setText(user.getName());
        txtFirstName.setText(user.getFirstName());
        txtLastName.setText(user.getLastName());
        txtEmail.setText(user.getEmail());
        txtPhone.setText("" + user.getPhone());
        txtCellPhone.setText("" + user.getCellPhone());
    }
}
