/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.DesktopApp.form.t_w;

import com.DesktopApp.ConstantUtils.WindowsManager;
import com.DesktopApp.Controller.UserController;
import com.DesktopApp.Entity.User;
import com.DesktopApp.InternalFrame.BaseJInternalFrame;
import com.DesktopApp.Utils.ContainerUtil;
import com.DesktopApp.modelTable.UserInqFormModelTable;
import com.itgp.mvc.DSetErrorEvent;
import java.io.IOException;

import java.util.List;

/**
 *
 * @author Jonathan
 */
public class UserInqForm extends BaseJInternalFrame {

    /**
     * Creates new form UserInqForm
     */
    public UserInqForm() {
        super("Formulario Usuarios", "Formulario encargado de la búsqueda de usuarios");
        initComponents();
        new UserInqFormModelTable(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dPanel1 = new com.itgp.mvc.DPanel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(835, 573));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        dPanel1.setPreferredSize(new java.awt.Dimension(700, 100));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 135));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(80, 70));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(628, 48));
        jPanel4.setLayout(null);

        lblName.setText("Nombre");
        jPanel4.add(lblName);
        lblName.setBounds(10, 20, 60, 25);
        jPanel4.add(txtName);
        txtName.setBounds(70, 20, 130, 25);

        jTabbedPane1.addTab("Búsqueda", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Estadística", jPanel5);

        jPanel1.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(633, 40));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/DesktopApp/Icon/search.png"))); // NOI18N
        btnSearch.setText("Buscar");
        btnSearch.setPreferredSize(new java.awt.Dimension(120, 30));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel6.add(btnSearch);
        btnSearch.getAccessibleContext().setAccessibleName("btnSearch");

        jPanel1.add(jPanel6, java.awt.BorderLayout.SOUTH);

        dPanel1.add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        dPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(394, 40));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/DesktopApp/Icon/userAdd.png"))); // NOI18N
        btnAdd.setText("Agregar");
        btnAdd.setPreferredSize(new java.awt.Dimension(120, 30));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdd);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/DesktopApp/Icon/userEdit.png"))); // NOI18N
        btnEdit.setText("Editar");
        btnEdit.setPreferredSize(new java.awt.Dimension(120, 30));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel3.add(btnEdit);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/DesktopApp/Icon/userDelete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel3.add(btnDelete);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/DesktopApp/Icon/cancel.png"))); // NOI18N
        btnClose.setText("Cerrar");
        btnClose.setPreferredSize(new java.awt.Dimension(120, 30));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel3.add(btnClose);

        dPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(dPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        new UserInqFormModelTable(jTable1);
        search(btnSearch);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int row = jTable1.getSelectedRow();

        if (row > -1) {
            Integer key = (Integer) jTable1.getValueAt(row, 0);
            UserForm f = new UserForm(WindowsManager.get(), key);
            ContainerUtil.setDefaultValues(f);
        }
        search(btnSearch);
    }//GEN-LAST:event_btnEditActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        this.dispose();
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        this.dispose();
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        UserForm f = new UserForm(WindowsManager.get(), 0);
        ContainerUtil.setDefaultValues(f);
        search(btnSearch);
    }//GEN-LAST:event_btnAddActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private com.itgp.mvc.DPanel dPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void doPopulateInquiry() {
        if (txtName.getText().trim().length() > 0) {
            List<User> list = UserController.getUserByName(txtName.getText().trim());
            UserInqFormModelTable.setTable(jTable1, list);
        } else {
            List<User> list = UserController.getAllUser();
            UserInqFormModelTable.setTable(jTable1, list);
        }
    }
}
